title: IsMoreiraKt
email: ismaelmoreirakt@gmail.com
description: A technology blog covering topics from C programming to the Segfault Project, including Linux rewritten in Ada.
baseurl: "/IsmaelMoreiraKt"
url: "https://ismoreirakt.github.io/IsmaelMoreiraKt"
github_username: IsMoreiraKt

theme: minima

plugins:
  - jekyll-feed
