title: IsMoreiraKt
email: ismaelmoreirakt@gmail.com
baseurl: "/IsmaelMoreiraKt"
url: "https://ismoreirakt.github.io/IsmaelMoreiraKt"
github_username: IsMoreiraKt
author: Ismael Moreira

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
