title: IsKt.tbss
email: ismaelmoreirakt@gmail.com
baseurl: "/iskt.tbss"
url: "https://ismoreirakt.github.io/iskt.tbss"
github_username: IsMoreiraKt
author: Ismael Moreira

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
